version: "3"
services:

  apache:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${STACK_VERSION}-apache-https.loadbalancer.server.port=80"
      - "traefik.http.routers.${STACK_VERSION}-apache-https.entrypoints=websecure"
      - "traefik.http.routers.${STACK_VERSION}-apache-https.rule=Host(`${INSTANCE_DOMAIN}`)"
      - "traefik.http.middlewares.${STACK_VERSION}-apache-auth.basicauth.users=${MOODLE_BASIC_AUTH_USERS}"
      - "traefik.http.routers.${STACK_VERSION}-apache-https.middlewares=${STACK_VERSION}-apache-auth"
      - "traefik.http.routers.${STACK_VERSION}-apache-https.tls=true"
      - "traefik.http.routers.${STACK_VERSION}-apache-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_VERSION}-apache-https.service=${STACK_VERSION}-apache-https"

  mailhog:
    image: mailhog/mailhog
    container_name: "${STACK_VERSION}_mailhog"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${STACK_VERSION}-mailhog-https.loadbalancer.server.port=8025"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.entrypoints=websecure"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.rule=Host(`mailhog${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
      - "traefik.http.middlewares.${STACK_VERSION}-mailhog-auth.basicauth.users=${MOODLE_BASIC_AUTH_USERS}"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.middlewares=${STACK_VERSION}-mailhog-auth"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.tls=true"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.service=${STACK_VERSION}-mailhog-https"
