#!/usr/bin/env bash

##
# Loop wrap: sync/enable a systemd --user unit for a long-running make entry.
#
# Gated helpers respect CWT_MONITORING / CWT_LOOP_MONITOR. Warns when linger is
# unavailable (reboot survival requires loginctl enable-linger).
#
# @param 1 String : make entry point name (e: prefix optional).
#
# @example
#   make loop-wrap e:blueprint-generate
#   cwt/loop/wrap.sh blueprint-generate
#

. cwt/bootstrap.sh

p_entry="${1:-}"
shift || true
p_entry="${p_entry#e:}"

if [[ -z "$p_entry" ]]; then
  echo >&2 "Usage: cwt/loop/wrap.sh <make-entry> [args...]"
  exit 1
fi

# Resolve make entry → script path.
make_entries=()
real_scripts=()
u_make_list_entry_points
p_script=''
for index in "${!make_entries[@]}"; do
  if [[ "${make_entries[index]}" == "$p_entry" ]]; then
    p_script="${real_scripts[index]}"
    break
  fi
done

if [[ -z "$p_script" || ! -f "$p_script" ]]; then
  echo >&2 "Error: unknown make entry '$p_entry'."
  exit 1
fi

p_args="$*"
# Stable instance id: entry + short hash of args (when present).
p_instance="$p_entry"
if [[ -n "$p_args" ]]; then
  p_hash="$(printf '%s' "$p_args" | sha256sum | awk '{print $1}')"
  p_instance="${p_entry}-${p_hash:0:8}"
fi

u_loop_warn_linger() {
  if ! command -v loginctl >/dev/null 2>&1; then
    echo >&2 "Warning: loginctl missing; loop unit may not survive logout."
    return 0
  fi
  local linger
  linger="$(loginctl show-user "${SUDO_USER:-$(id -un)}" -p Linger --value 2>/dev/null || echo no)"
  case "$linger" in
    yes|YES|1) ;;
    *)
      echo >&2 "Warning: user linger is off — reboot/logout survival needs: loginctl enable-linger"
      ;;
  esac
}

u_loop_wrap_enabled_monitor() {
  case "${CWT_MONITORING:-1}" in 0|false|FALSE|off|OFF) return 1 ;; esac
  case "${CWT_LOOP_MONITOR:-1}" in 0|false|FALSE|off|OFF) return 1 ;; esac
  return 0
}

if ! command -v systemctl >/dev/null 2>&1; then
  echo >&2 "Error: systemctl not available; cannot loop-wrap."
  exit 1
fi

if ! systemctl --user status >/dev/null 2>&1; then
  echo >&2 "Error: systemd user bus unavailable; cannot loop-wrap."
  exit 1
fi

u_loop_warn_linger
mkdir -p data/cwt/loop "$HOME/.config/systemd/user"

unit_name="cwt-loop@${p_instance}.service"
unit_path="$HOME/.config/systemd/user/${unit_name}"

# Template instance unit (simple ExecStart → make -C PROJECT_DOCROOT entry args).
exec_start="/usr/bin/make -C $(printf '%q' "${PROJECT_DOCROOT:-$PWD}") ${p_entry}"
if [[ -n "$p_args" ]]; then
  exec_start+=" ${p_args}"
fi

cat > "$unit_path" <<EOF
[Unit]
Description=CWT loop ${p_instance}
After=default.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_DOCROOT:-$PWD}
ExecStart=${exec_start}
Restart=on-failure
RestartSec=5
Environment=CWT_WRAP_NONINTERACTIVE=1
Environment=CWT_LOOP_INSTANCE=${p_instance}

[Install]
WantedBy=default.target
EOF

# Registry for loop-status / CRUD.
cat > "data/cwt/loop/${p_instance}.sh" <<EOF
#!/usr/bin/env bash
# Generated by loop/wrap — do not hand-edit as SoT.
export CWT_LOOP_INSTANCE='${p_instance}'
export CWT_LOOP_ENTRY='${p_entry}'
export CWT_LOOP_ARGS='${p_args}'
export CWT_LOOP_UNIT='${unit_name}'
export CWT_LOOP_UNIT_PATH='${unit_path}'
export CWT_LOOP_RESTART='on-failure'
EOF

systemctl --user daemon-reload
systemctl --user enable --now "$unit_name"

echo "Loop started: $unit_name"
echo "  entry  : $p_entry $p_args"
echo "  unit   : $unit_path"
echo "  status : make loop-status e:$p_instance  (or systemctl --user status $unit_name)"

if u_loop_wrap_enabled_monitor; then
  u_hook_most_specific 'dry-run' -s 'loop' -a 'monitor' \
    -v 'STACK_VERSION PROVISION_USING HOST_TYPE HOST_OS' || true
  if [[ -n "${hook_most_specific_dry_run_match:-}" && -f "$hook_most_specific_dry_run_match" ]]; then
    # shellcheck disable=SC1090
    . "$hook_most_specific_dry_run_match" "$p_instance" || true
  fi
fi
