entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: {{ TRAEFIK_CERT_EMAIL }}
      storage: acme.json
      httpChallenge:
        entryPoint: web
