version: "3"
services:

  # See https://github.com/wodby/nginx
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${DC_NS}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
      NGINX_STATIC_404_TRY_INDEX: 1
      NGINX_SERVER_ROOT: $SERVER_DOCROOT_C
      NGINX_CLIENT_MAX_BODY_SIZE: 144M
    restart: on-failure:5
    volumes:
      - ./$APP_DOCROOT:$APP_DOCROOT_C

  # See https://github.com/wodby/mariadb
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${DC_NS}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ADMIN_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    restart: on-failure:5
    volumes:
      - mariadb_volume:/var/lib/mysql

  # See https://github.com/wodby/php
  # See https://github.com/wodby/drupal-php
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${DC_NS}_php"
    depends_on:
      - "mariadb"
    environment:
      DB_HOST: $DB_HOST
      DB_DRIVER: $DB_DRIVER
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASS
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PHP_POST_MAX_SIZE: 144M
      COLUMNS: 80
      # Custom PHP env vars - example use from Php scripts :
      # <?php $host_type = getenv('HOST_TYPE');
      HOST_TYPE: $HOST_TYPE
      INSTANCE_TYPE: $INSTANCE_TYPE
      INSTANCE_DOMAIN: $INSTANCE_DOMAIN
    volumes:
      - ./$APP_DOCROOT:$APP_DOCROOT_C
      - $DRUPAL_TMP_DIR:$DRUPAL_TMP_DIR_C
      - $DRUPAL_PRIVATE_DIR:$DRUPAL_PRIVATE_DIR_C

  crond:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${DC_NS}_crond"
    environment:
      CRONTAB: "${DWT_CRON_FREQ} drush -r ${APP_DOCROOT_C} cron"
      DB_HOST: $DB_HOST
      DB_DRIVER: $DB_DRIVER
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASS
      COLUMNS: 80
      # Custom PHP env vars - example use from Php scripts :
      # <?php $host_type = getenv('HOST_TYPE');
      HOST_TYPE: $HOST_TYPE
      INSTANCE_TYPE: $INSTANCE_TYPE
      INSTANCE_DOMAIN: $INSTANCE_DOMAIN
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
      - ./$APP_DOCROOT:$APP_DOCROOT_C
      - $DRUPAL_TMP_DIR:$DRUPAL_TMP_DIR_C
      - $DRUPAL_PRIVATE_DIR:$DRUPAL_PRIVATE_DIR_C

  # See https://github.com/wodby/redis
  redis:
    image: wodby/redis:$REDIS_TAG
    container_name: "${DC_NS}_redis"
    restart: on-failure:5

volumes:
  mariadb_volume:
