version: "3"
services:

  # See https://github.com/wodby/nginx
  nginx:
    labels:
      - traefik.http.routers.${DC_NS}_nginx_http.rule=Host(`${INSTANCE_DOMAIN}`)
      - traefik.http.routers.${DC_NS}_nginx_http.entrypoints=http
      - traefik.http.routers.${DC_NS}_nginx_http.middlewares=redirect
      - traefik.http.routers.${DC_NS}_nginx_https.rule=Host(`${INSTANCE_DOMAIN}`)
      - traefik.http.routers.${DC_NS}_nginx_https.entrypoints=https
      - traefik.http.routers.${DC_NS}_nginx_https.tls=true
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
