version: "3"
services:

  php:
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025

  # See https://github.com/wodby/adminer
  adminer:
    image: wodby/adminer:$ADMINER_TAG
    container_name: "${DC_NS}_adminer"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: $DB_DRIVER
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    labels:
      - "traefik.http.services.${DC_NS}_adminer.loadbalancer.server.port=9000"
      - "traefik.http.routers.${DC_NS}_adminer.rule=Host(`adminer.${INSTANCE_DOMAIN}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${DC_NS}_mailhog"
    labels:
      - "traefik.http.services.${DC_NS}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${DC_NS}_mailhog.rule=Host(`mailhog.${INSTANCE_DOMAIN}`)"
