version: "3"
services:

  # See https://github.com/wodby/nginx
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DC_NS}-nginx-https.entrypoints=websecure"
      - "traefik.http.routers.${DC_NS}-nginx-https.rule=Host(`${INSTANCE_DOMAIN}`)"
      - "traefik.http.routers.${DC_NS}-nginx-https.tls=true"
      - "traefik.http.routers.${DC_NS}-nginx-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${DC_NS}-nginx-https.service=${DC_NS}-nginx-https"
