version: "3"
services:

  # TODO [evol] Switch to port 80 + default domain by default if enabled ?
  # varnish:
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.${DC_NS}-varnish-https.loadbalancer.server.port=6081"
  #     - "traefik.http.routers.${DC_NS}-varnish-https.rule=Host(`varnish${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
  #     - "traefik.http.routers.${DC_NS}-varnish-https.tls=true"
  #     - "traefik.http.routers.${DC_NS}-varnish-https.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.${DC_NS}-varnish-https.service=${DC_NS}-varnish-https"

  # TODO [evol] Allocate port 80 + default domain to Varnish by default if
  # enabled ?
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${DC_NS}-nginx-https.loadbalancer.server.port=80"
      - "traefik.http.routers.${DC_NS}-nginx-https.entrypoints=websecure"
      - "traefik.http.routers.${DC_NS}-nginx-https.rule=Host(`${INSTANCE_DOMAIN}`)"
      - "traefik.http.routers.${DC_NS}-nginx-https.tls=true"
      - "traefik.http.routers.${DC_NS}-nginx-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${DC_NS}-nginx-https.service=${DC_NS}-nginx-https"
