version: "3"
services:

  # TODO [evol] Switch to port 80 + default domain by default if enabled ?
  # varnish:
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.${STACK_VERSION}-varnish-https.loadbalancer.server.port=6081"
  #     - "traefik.http.routers.${STACK_VERSION}-varnish-https.rule=Host(`varnish${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
  #     - "traefik.http.middlewares.${STACK_VERSION}-varnish-auth.basicauth.users=${D4D_BASIC_AUTH_USERS}"
  #     - "traefik.http.routers.${STACK_VERSION}-varnish-https.middlewares=${STACK_VERSION}-varnish-auth"
  #     - "traefik.http.routers.${STACK_VERSION}-varnish-https.tls=true"
  #     - "traefik.http.routers.${STACK_VERSION}-varnish-https.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.${STACK_VERSION}-varnish-https.service=${STACK_VERSION}-varnish-https"

  # TODO [evol] Allocate port 80 + default domain to Varnish by default if
  # enabled ?
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${STACK_VERSION}-nginx-https.loadbalancer.server.port=80"
      - "traefik.http.routers.${STACK_VERSION}-nginx-https.entrypoints=websecure"
      - "traefik.http.routers.${STACK_VERSION}-nginx-https.rule=Host(`${INSTANCE_DOMAIN}`)"
      - "traefik.http.middlewares.${STACK_VERSION}-nginx-auth.basicauth.users=${D4D_BASIC_AUTH_USERS}"
      - "traefik.http.routers.${STACK_VERSION}-nginx-https.middlewares=${STACK_VERSION}-nginx-auth"
      - "traefik.http.routers.${STACK_VERSION}-nginx-https.tls=true"
      - "traefik.http.routers.${STACK_VERSION}-nginx-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_VERSION}-nginx-https.service=${STACK_VERSION}-nginx-https"

  php:
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025

  # See https://github.com/wodby/adminer
  adminer:
    image: wodby/adminer:$ADMINER_TAG
    container_name: "${STACK_VERSION}_adminer"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: $DB_DRIVER
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${STACK_VERSION}-adminer-https.loadbalancer.server.port=9000"
      - "traefik.http.routers.${STACK_VERSION}-adminer-https.entrypoints=websecure"
      - "traefik.http.routers.${STACK_VERSION}-adminer-https.rule=Host(`adminer${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
      - "traefik.http.middlewares.${STACK_VERSION}-adminer-auth.basicauth.users=${D4D_BASIC_AUTH_USERS}"
      - "traefik.http.routers.${STACK_VERSION}-adminer-https.middlewares=${STACK_VERSION}-adminer-auth"
      - "traefik.http.routers.${STACK_VERSION}-adminer-https.tls=true"
      - "traefik.http.routers.${STACK_VERSION}-adminer-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_VERSION}-adminer-https.service=${STACK_VERSION}-adminer-https"

  mailhog:
    image: mailhog/mailhog
    container_name: "${STACK_VERSION}_mailhog"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${STACK_VERSION}-mailhog-https.loadbalancer.server.port=8025"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.entrypoints=websecure"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.rule=Host(`mailhog${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
      - "traefik.http.middlewares.${STACK_VERSION}-mailhog-auth.basicauth.users=${D4D_BASIC_AUTH_USERS}"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.middlewares=${STACK_VERSION}-mailhog-auth"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.tls=true"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${STACK_VERSION}-mailhog-https.service=${STACK_VERSION}-mailhog-https"

  # solr:
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.${STACK_VERSION}-solr-https.loadbalancer.server.port=8983"
  #     - "traefik.http.routers.${STACK_VERSION}-solr-https.rule=Host(`solr${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
  #     - "traefik.http.middlewares.${STACK_VERSION}-solr-auth.basicauth.users=${D4D_BASIC_AUTH_USERS}"
  #     - "traefik.http.routers.${STACK_VERSION}-solr-https.middlewares=${STACK_VERSION}-solr-auth"
  #     - "traefik.http.routers.${STACK_VERSION}-solr-https.tls=true"
  #     - "traefik.http.routers.${STACK_VERSION}-solr-https.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.${STACK_VERSION}-solr-https.service=${STACK_VERSION}-solr-https"

  # tika:
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.${STACK_VERSION}-tika-https.loadbalancer.server.port=9998"
  #     - "traefik.http.routers.${STACK_VERSION}-tika-https.rule=Host(`tika${DC_SUBDOMAIN_SEP}${INSTANCE_DOMAIN}`)"
  #     - "traefik.http.middlewares.${STACK_VERSION}-tika-auth.basicauth.users=${D4D_BASIC_AUTH_USERS}"
  #     - "traefik.http.routers.${STACK_VERSION}-tika-https.middlewares=${STACK_VERSION}-tika-auth"
  #     - "traefik.http.routers.${STACK_VERSION}-tika-https.tls=true"
  #     - "traefik.http.routers.${STACK_VERSION}-tika-https.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.${STACK_VERSION}-tika-https.service=${STACK_VERSION}-tika-https"
